name = "backend1"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmE3N2EwZjctY2I0MS00MGYyLTg4OWYtNzc4YTlkNWUxYTJjIiwidGVuYW50X2lkIjoiMWM0MDdkYjcwMjA3M2IzMTM4ZDIyMTVlNDgwZTViZGMyZTZmNTk0NTZkYmE4MzYxNWExZjg3NGIyZmE0ODVjZCIsImludGVybmFsX3NlY3JldCI6ImU1ZWE5NzUwLWIzYTUtNDg0Mi04MDVjLTgzYmRhOTQ5Nzk0YiJ9.zJ67SAMlWiQDNH0nq04WPNVW2nIsYTj4CobsRIfKTFE"
JWT_SECRET = "vivek"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"